// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "MGTheTrain"
        },
        "license": {
            "name": "MIT license",
            "url": "https://github.com/MGTheTrain/crypto-vault-service/blob/main/LICENSE"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/blobs": {
            "get": {
                "description": "Fetch a list of metadata for blobs based on query filters like name, size, type, and creation date.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Blob"
                ],
                "summary": "List blob metadata based on query parameters",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Blob Name",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Blob Size",
                        "name": "size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Blob Type",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Blob Creation Date (RFC3339)",
                        "name": "dateTimeCreated",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Limit the number of results",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Offset the results",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/v1.BlobMetaResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/v1.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Upload a blob to the system with optional encryption and signing using the provided keys",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Blob"
                ],
                "summary": "Upload a blob with optional encryption and signing",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Blob File",
                        "name": "files",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Encryption Key ID",
                        "name": "encryption_key_id",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Sign Key ID",
                        "name": "sign_key_id",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/v1.BlobMetaResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/blobs/{id}": {
            "get": {
                "description": "Fetch the blob metadata by ID, including name, size, type, encryption and signing key IDs, and creation date.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Blob"
                ],
                "summary": "Retrieve blob metadata by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Blob ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.BlobMetaResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/v1.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a specific blob and associated metadata by ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Blob"
                ],
                "summary": "Delete a blob by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Blob ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "$ref": "#/definitions/v1.InfoResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/v1.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/blobs/{id}/file": {
            "get": {
                "description": "Download the content of a specific blob by ID, optionally decrypted with a provided decryption key ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "Blob"
                ],
                "summary": "Download a blob by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Blob ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Decryption Key ID",
                        "name": "decryption_key_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Blob content",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/v1.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/blobs/{id}/signature": {
            "get": {
                "description": "Download the signature file associated with a specific blob",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "Blob"
                ],
                "summary": "Download a blob's signature by blob ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Blob ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Signature file content",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/v1.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/keys": {
            "get": {
                "description": "Fetch a list of cryptographic key metadata based on filters like algorithm, type and creation date, with pagination and sorting options.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Key"
                ],
                "summary": "List cryptographic key metadata based on query parameters",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Cryptographic Algorithm",
                        "name": "algorithm",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Key Type",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Key Creation Date (RFC3339)",
                        "name": "dateTimeCreated",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Limit the number of results",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Offset the results",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort by a specific field",
                        "name": "sortBy",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort order (asc/desc)",
                        "name": "sortOrder",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/v1.CryptoKeyMetaResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/v1.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Generate cryptographic keys based on provided parameters and upload them to the system.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Key"
                ],
                "summary": "Upload cryptographic keys and metadata",
                "parameters": [
                    {
                        "description": "Cryptographic Key Data",
                        "name": "requestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.UploadKeyRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/v1.CryptoKeyMetaResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/keys/{id}": {
            "get": {
                "description": "Fetch the crypto key metadata by ID, including algorithm, key size and creation date.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Key"
                ],
                "summary": "Retrieve crypto key metadata by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Key ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.CryptoKeyMetaResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/v1.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a specific cryptographic key and associated metadata by ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Key"
                ],
                "summary": "Delete a cryptographic key by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Key ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "$ref": "#/definitions/v1.InfoResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/v1.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/keys/{id}/file": {
            "get": {
                "description": "Download the content of a specific cryptographic key by ID in PEM format.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/x-pem-file"
                ],
                "tags": [
                    "Key"
                ],
                "summary": "Download a cryptographic key by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Key ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Cryptographic key content in PEM format",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/v1.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "v1.BlobMetaResponse": {
            "type": "object",
            "properties": {
                "dateTimeCreated": {
                    "description": "Timestamp when the blob was created",
                    "type": "string"
                },
                "encryptionKeyID": {
                    "description": "Optional encryption key ID for the blob",
                    "type": "string"
                },
                "id": {
                    "description": "Unique identifier for the blob",
                    "type": "string"
                },
                "name": {
                    "description": "Name of the blob",
                    "type": "string"
                },
                "signKeyID": {
                    "description": "Optional signature key ID for the blob",
                    "type": "string"
                },
                "signatureBlobID": {
                    "type": "string"
                },
                "signatureFileName": {
                    "type": "string"
                },
                "size": {
                    "description": "Size of the blob in bytes",
                    "type": "integer"
                },
                "type": {
                    "description": "Type of the blob (e.g., file format)",
                    "type": "string"
                },
                "userID": {
                    "description": "User who uploaded the blob",
                    "type": "string"
                }
            }
        },
        "v1.CryptoKeyMetaResponse": {
            "type": "object",
            "properties": {
                "algorithm": {
                    "description": "Cryptographic algorithm (e.g., AES, RSA, EC)",
                    "type": "string"
                },
                "dateTimeCreated": {
                    "description": "Timestamp when the key was created",
                    "type": "string"
                },
                "id": {
                    "description": "Unique identifier for the cryptographic key",
                    "type": "string"
                },
                "keyPairID": {
                    "description": "Identifier for the key pair the key belongs to",
                    "type": "string"
                },
                "keySize": {
                    "description": "Size of the cryptographic key",
                    "type": "integer"
                },
                "type": {
                    "description": "Type of the cryptographic key (e.g., public, private)",
                    "type": "string"
                },
                "userID": {
                    "description": "User who created the key",
                    "type": "string"
                }
            }
        },
        "v1.ErrorResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "description": "The error message",
                    "type": "string"
                }
            }
        },
        "v1.InfoResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "description": "The informational message",
                    "type": "string"
                }
            }
        },
        "v1.UploadKeyRequest": {
            "type": "object",
            "properties": {
                "algorithm": {
                    "type": "string",
                    "enum": [
                        "AES",
                        "RSA",
                        "ECDSA"
                    ]
                },
                "key_size": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        },
        "BasicAuth": {
            "type": "basic"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "v1",
	Host:             "",
	BasePath:         "/api/v1/cvs",
	Schemes:          []string{},
	Title:            "CryptoVault Service API",
	Description:      "Service capable of managing cryptographic keys and securing data at rest",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
